name: Deploy to EC2 on Master Commit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up SSH to communicate with EC2 instance
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Set this in your GitHub secrets
    
    # SSH into EC2 and deploy the project
    - name: Deploy on EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Stop the running project by killing any npm or node process
          pkill -f "npm" || true  # or "pkill -f 'node'" if npm is not working

          # Remove the existing project directory and clone fresh from GitHub
          rm -rf /path/to/your/project
          git clone https://github.com/your-username/your-repository.git /path/to/your/project

          # Change to project directory
          cd /path/to/your/project

          # Install dependencies
          npm install

          # Run tests
          npm test
          TEST_RESULT=$?

          # Check if tests passed
          if [ $TEST_RESULT -eq 0 ]; then
            echo "Deployment successful: Tests passed!"
            
            # Restart the project after success
            npm start &
          else
            echo "Deployment failed: Tests did not pass."
            exit 1
          fi
        EOF

    # Notify if deployment was successful or failed
    - name: Notify success/failure
      if: success()
      run: echo "Deployment to EC2 was successful!"

    - name: Notify failure
      if: failure()
      run: echo "Deployment to EC2 failed due to test failure."
